/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'd.roserosette' at '12/03/18 15:27' with Gradle 3.0
 *
 * @author d.roserosette, @date 12/03/18 15:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
